# Generated by Django 6.0.2 on 2026-02-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
