# Generated by Django 6.0.2 on 2026-02-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(verbose_name='-'),
        ),
    ]
