# Generated by Django 6.0.2 on 2026-02-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0004_alter_product_slug'),
    ]

    operations = [
    ]
